# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(586, 464)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.date_select = QtWidgets.QLabel(self.centralwidget)
        self.date_select.setObjectName("date_select")
        self.horizontalLayout_2.addWidget(self.date_select)
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_2.addWidget(self.dateEdit)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setObjectName("image")
        self.verticalLayout.addWidget(self.image)
        self.date = QtWidgets.QLabel(self.centralwidget)
        self.date.setObjectName("date")
        self.verticalLayout.addWidget(self.date)
        self.copyright = QtWidgets.QLabel(self.centralwidget)
        self.copyright.setObjectName("copyright")
        self.verticalLayout.addWidget(self.copyright)
        self.explanation = QtWidgets.QLabel(self.centralwidget)
        self.explanation.setObjectName("explanation")
        self.verticalLayout.addWidget(self.explanation)
        self.download = QtWidgets.QPushButton(self.centralwidget)
        self.download.setObjectName("download")
        self.verticalLayout.addWidget(self.download)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 586, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "APOD"))
        self.date_select.setText(_translate("MainWindow", "Выбирете дату:"))
        self.pushButton.setText(_translate("MainWindow", "Загрузить"))
        self.title.setText(_translate("MainWindow", "TextLabel"))
        self.image.setText(_translate("MainWindow", "TextLabel"))
        self.date.setText(_translate("MainWindow", "TextLabel"))
        self.copyright.setText(_translate("MainWindow", "TextLabel"))
        self.explanation.setText(_translate("MainWindow", "TextLabel"))
        self.download.setText(_translate("MainWindow", "Сохранить изображние"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
